parameters:
    badges:
        artwork:
          1: 1
          2: 20
          3: 200
          4 : 750
          5 : 2000
        artist:
          1: 1
          2: 5
          3: 20
          4: 50
          5: 100
        city:
          1: 1
          2: 5
          3: 20
          4: 50
          5: 100
        country:
          1: 1
          2: 5
          3: 10
          4: 20
          5: 50
        same_artist:
          1: 1
          2: 5
          3: 20
          4: 50
          5: 100
        same_city:
          1: 1
          2: 10
          3: 50
          4: 100
          5: 500
        same_country:
          1: 1
          2: 10
          3: 100
          4: 500
          5: 1000
        profil_hunter:
          1: 10
          2: 50
          3: 100
          4: 1000
          5: 5000
        profil_hunter_artwork:
          1: 100
          2: 500
          3: 2000
          4: 5000
          5: 10000
        insta:
          1: 1
          2: 2
          3: 10
          4: 50
          5: 100