parameters:
    badges:
        artwork:
          1: 1
          20: 2
          200: 3
          750 : 4
          2000 : 5
        artist:
          1: 1
          5: 2
          20: 3
          50: 4
          100: 5
        city:
          1: 1
          5: 2
          20: 3
          50: 4
          100: 5
        country:
          1: 1
          5: 2
          10: 3
          20: 4
          50: 5
        same_artist:
          1: 1
          5: 2
          20: 3
          50: 4
          100: 5
        same_city:
          1: 1
          10: 2
          50: 3
          100: 4
          500: 5
        same_country:
          1: 1
          10: 2
          100: 3
          500: 4
          1000: 5
        profil_hunter:
          10: 1
          50: 2
          100: 3
          1000: 4
          5000: 5
        profil_hunter_artwork:
          100: 1
          500: 2
          2000: 3
          5000: 4
          10000: 5
        insta:
          1: 1
          5: 2
          10: 3
          50: 4
          100: 5