parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '10'

        schema_filter: /^(?!tiger|topology).*$/


        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
        types:
            geography:
                class: 'Jsor\Doctrine\PostGIS\Types\GeographyType'
                commented: false
            geometry:
                class: 'Jsor\Doctrine\PostGIS\Types\GeometryType'
                commented: false
            raster:
                class: 'Jsor\Doctrine\PostGIS\Types\RasterType'
                commented: false
        mapping_types:
          _text: string
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                Geometry:             Jsor\Doctrine\PostGIS\Functions\Geometry
                Geography:            Jsor\Doctrine\PostGIS\Functions\Geography
                ST_Distance:          Jsor\Doctrine\PostGIS\Functions\ST_Distance
                ST_Distance_Sphere:   Jsor\Doctrine\PostGIS\Functions\ST_Distance_Sphere
                ST_DWithin:           Jsor\Doctrine\PostGIS\Functions\ST_DWithin
                ST_GeomFromText:      Jsor\Doctrine\PostGIS\Functions\ST_GeomFromText
                ST_GeographyFromText: Jsor\Doctrine\PostGIS\Functions\ST_GeographyFromText
                ST_Transform:         Jsor\Doctrine\PostGIS\Functions\ST_Transform
                ST_Point:             Jsor\Doctrine\PostGIS\Functions\ST_Point
                ST_SetSRID:           Jsor\Doctrine\PostGIS\Functions\ST_SetSRID
                ST_AsEWKT:            Jsor\Doctrine\PostGIS\Functions\ST_AsEWKT