parameters:
    # Adds a fallback MAILER_USER if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(MAILER_USER): ''

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: '%env(resolve:MAILER_USER)%'
        sender_name: '%env(resolve:MAILER_USER)%'
    registration:
        form:
           type: App\Form\Type\RegistrationType
    profile:
        form:
           type: App\Form\Type\ProfileType