hwi_oauth:
    firewall_names: [main]
    resource_owners:
          facebook:
              type:                facebook
              client_id:           '%env(resolve:FB_ID)%'
              client_secret:       '%env(resolve:FB_SECRET)%'
              scope:               email
              infos_url:           "https://graph.facebook.com/me?fields=email,first_name,last_name,name,picture.type(square),id"
              paths:
                email: email
                firstname: first_name
                lastname: last_name
                profilepicture: picture
          instagram:
              type:                instagram
              client_id:           '%env(resolve:INST_ID)%'
              client_secret:       '%env(resolve:INST_SECRET)%'
              paths:
                email: email
                firstname: first_name
                lastname: last_name
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookId
            instagram: instagramId