liip_imagine:
    loaders:
        default:
            filesystem:
                bundle_resources:
                    enabled: true
                data_root: "%kernel.project_dir%/public"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
    driver: imagick
    filter_sets:
#        cache: ~

        thumb_small:
            quality: 75
            filters:
                thumbnail: { size: [350, 260], mode: outbound }

        thumb_small_square:
            quality: 75
            filters:
                thumbnail: { size: [360, 360], mode: outbound }

        thumb_smaller:
            quality: 75
            filters:
                thumbnail: { size: [105, 78], mode: outbound }

        thumb_smallmedium:
            quality: 75
            filters:
                thumbnail: { size: [210, 156], mode: outbound }

        thumb_large:
            quality: 75
            filters:
                thumbnail: { size: [1680, 1248], mode: outbound }
