vich_uploader:
    db_driver: orm

    mappings:
        document_image:
            uri_prefix: /uploads/document
            upload_destination: '%kernel.project_dir%/public/uploads/document'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
