version: '3.6'

services:
    db:
        image: mdillon/postgis:10
        volumes:
            - db-data:/usr/local/var/postgres
        ports:
            - 5432:5432
        environment:
            - DEBUG=false
            - POSTGRES_USER=streetart
            - POSTGRES_PASSWORD=streetart
            - POSTGRES_DB=streetart

networks:
    backend:

volumes:
    db-data: