version: '3.6'

services:

    web:
        image: nginx:latest
        ports:
            - 80:80
        networks:
            - backend
        depends_on:
            - php
        volumes:
            - .:/app
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

    php:
        build:
            context: .
            dockerfile: docker/Dockerfile-php.dev.conf
        command: /app/docker/start-php.dev.sh
        networks:
            - backend
        depends_on:
            - db
        volumes:
            - .:/app

    db:
        image: mdillon/postgis:10
        volumes:
            - db-data:/usr/local/var/postgres
        networks:
            - backend
        ports:
            - 5432:5432
        environment:
            - DEBUG=false
            - POSTGRES_USER=streetart
            - POSTGRES_PASSWORD=streetart
            - POSTGRES_DB=streetart

    mailcatcher:
        image: yappabe/mailcatcher
        networks:
            - backend
        ports:
            - 1025:1025
            - 1080:1080

networks:
    backend:

volumes:
    db-data: