version: '3.6'

services:

    web:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        networks:
            - backend
        depends_on:
            - php
        volumes:
            - .:/app:delegated
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/streetartwork.com.crt:/etc/nginx/ssl/streetartwork.com.crt
            - ./docker/streetartwork.com.key:/etc/nginx/ssl/streetartwork.com.key
            - ./var/log/xdebug_remote.log:/var/log/xdebug_remote.log

    php:
        build:
            context: .
            dockerfile: docker/Dockerfile-php.dev.conf
        command: /app/docker/start-php.dev.sh
        networks:
            - backend
        depends_on:
            - db
        volumes:
            - .:/app:delegated
        environment:
          XDEBUG_CONFIG: remote_host={{172.18.0.4}}

    db:
        image: mdillon/postgis:10
        volumes:
            - db-data:/usr/local/var/postgres
        networks:
            - backend
        ports:
            - 5432:5432
        environment:
            - DEBUG=false
            - POSTGRES_USER=streetart
            - POSTGRES_PASSWORD=streetart
            - POSTGRES_DB=streetart

    mailcatcher:
        image: yappabe/mailcatcher
        networks:
            - backend
        ports:
            - 1025:1025
            - 1080:1080

networks:
    backend:

volumes:
    db-data: