fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /{_locale}


fos_user_registration_confirmed:
    path: /{_locale}/register/confirmed
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: dashboard
        # make a permanent redirection...
        permanent: true
        # ...and keep the original query string parameters
        keepQueryParams: true


fos_user_profile_show:
    path: /{_locale}/profile
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: dashboard
        # make a permanent redirection...
        permanent: true
        # ...and keep the original query string parameters
        keepQueryParams: true