App\Entity\Poi:

    attributes:
        normalization_context:
            groups: ['poi_read']
        denormalization_context:
            groups: ['poi_read']
    itemOperations:
        get:
            method: 'GET'
    collectionOperations:
         get:
            method: 'GET'
            filters: [App\Filter\LocationFilter]
