version: 2

workflows:
  version: 2
  build:
    jobs:
      - build
      - phpstan:
          requires:
            - build
      - php-metrics
      - php-phpmd
      - php-cs-fixer

jobs:

  build:
    working_directory: ~/street-art
    # The primary container is an instance of the first list image listed. Your {% comment %} TODO: Job {% endcomment %}build commands run in this container.
    docker:
      - image: myprod/php:7.2

    steps:
      - checkout
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.composer/cache

      # setup initial tools
      - run:
          name: Init system dependencies
          command: cp .env.dist .env

      # install composer dependencies
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

#      # install npm dependencies
#      - run:
#          name: Update npm
#          command: 'sudo npm install -g npm@latest'
#
#      - restore_cache:
#          keys:
#            - node-v1-{{ checksum "package.json" }}
#            - node-v1-
#      - run: npm install
#      - save_cache:
#          key: node-v1-{{ checksum "package.json" }}
#          paths:
#            - node_modules

  phpstan:
    working_directory: ~/street-art
    docker:
      - image: jakzal/phpqa
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: ls -lah vendor
      - run: composer install --prefer-dist
      - run: phpstan analyse --level 2 -c .circleci/tools/phpstan.neon src

  php-metrics:
    working_directory: ~/street-art
    docker:
      - image: jakzal/phpqa
    steps:
      - checkout
      - run: phpmetrics --report-html=var/php-metrics src
      - store_artifacts:
          path: "var/php-metrics/"

  php-phpmd:
    working_directory: ~/street-art
    docker:
      - image: jakzal/phpqa
    steps:
      - checkout
      - run: phpmd src text .circleci/tools/phpmd.xml
      - store_artifacts:
          path: "var/phpmd.html"

  php-cs-fixer:
    working_directory: ~/street-art
    docker:
      - image: jakzal/phpqa
    steps:
      - checkout
      - run: .circleci/tools/php-cs-fixer.sh
      - store_artifacts:
          path: "var/patch.diff"



