version: 2
machine:
  php:
    version: 7.1.3

jobs:
  build:
      docker:
        - image: circleci/python:3.6.1
      steps:
        - checkout
        - run: ls -al

dependencies:
  pre:
    - mkdir -p ~/.composer/cache
    - mkdir -p ~/.php-cs-fixer
    - echo "memory_limit = 256M" > /opt/circleci/php/$(phpenv global)/etc/conf.d/memory.ini
  override:
    - composer install --prefer-dist --optimize-autoloader --no-interaction --no-scripts
    - vendor/bin/php-cs-fixer fix --config=.php_cs.dist --cache-file ~/.php-cs-fixer/.php_cs.cache --diff --verbose
  cache_directories:
    - ~/.composer/cache
    - ~/.php-cs-fixer

test:
  override:
    - mkdir -p $CIRCLE_TEST_REPORTS/phpunit
#    - vendor/bin/phpunit --log-junit $CIRCLE_TEST_REPORTS/phpunit/junit.xml
#    - mkdir -p $CIRCLE_TEST_REPORTS/behat
#    - vendor/bin/behat --out $CIRCLE_TEST_REPORTS/behat/test.log
  post:
    - FILES_WITHOUT_LF_AT_EOF=$(for file in $(git grep --cached -Il ''); do test $(tail -c 1 $file) && echo $file; done); if [[ -n $FILES_WITHOUT_LF_AT_EOF ]]; then echo -e "Some files have missing LF at EOF:\n$FILES_WITHOUT_LF_AT_EOF" && exit 1; fi;
    - FILES_WITH_TRAILING_WHITESPACES=$(git grep --cached -Il " $"); if [[ $FILES_WITH_TRAILING_WHITESPACES ]]; then echo -e "Some files have trailing whitespaces at line endings:\n$FILES_WITH_TRAILING_WHITESPACES" && exit 1; fi;
    - vendor/bin/phpmd src/ text phpmd.xml.dist --ignore-violations-on-exit