#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path:         /
    controller:   App\Controller\HomeController
    defaults:
        template: pages/home.html.twig

map:
    path:         /map
    controller:   App\Controller\MapController
    defaults:
        template: pages/map.html.twig
#    requirements:
#        _locale:  en|fr

faq:
    path:         /faq
    controller:   App\Controller\FaqController
    defaults:
        template: pages/content.html.twig