home:
    path:         /{_locale}
    controller:   App\Controller\HomeController
    defaults:
        template: pages/home.html.twig
        _locale:  fr
    requirements:
        _locale:  '%locale_available%'

map:
    path:         /{_locale}/map
    controller:   App\Controller\MapController
    defaults:
        template: pages/map.html.twig
    requirements:
        _locale:  '%locale_available%'

list:
    path:         /{_locale}/list/{page}
    controller:   App\Controller\ListController
    defaults:
        template: pages/list.html.twig
        page:     1
    requirements:
        _locale:  '%locale_available%'

search:
    path:         /{_locale}/search/{queryRequest}
    controller:   App\Controller\SearchController
    defaults:
        template: pages/list.html.twig
    requirements:
        _locale:  '%locale_available%'

faq:
    path:         /{_locale}/faq
    controller:   App\Controller\FaqController
    defaults:
        template: pages/content.html.twig
    requirements:
        _locale:  '%locale_available%'

sitemap:
    path:         /{_locale}/sitemap
    controller:   App\Controller\SitemapController
    defaults:
        template: pages/content.html.twig
    requirements:
        _locale:  '%locale_available%'

legals:
    path:         /{_locale}/legals
    controller:   App\Controller\LegalsController
    defaults:
        template: pages/content.html.twig
    requirements:
        _locale:  '%locale_available%'

blog:
    path:         /{_locale}/blog/{id}
    controller:   App\Controller\BlogController
    defaults:
        template: pages/content.html.twig
    requirements:
        id:  "[a-zA-Z0-9-]+"
        _locale:  '%locale_available%'

artwork:
    path:         /{_locale}/artwork/{id}
    controller:   App\Controller\ArtworkController
    defaults:
        template: pages/artwork.html.twig
    requirements:
        id:  "[0-9]+"
        _locale:  '%locale_available%'

welcome:
    path:         /{_locale}/welcome
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: pages/welcome.html.twig
    requirements:
        _locale:  '%locale_available%'

dashboard:
    path:         /{_locale}/dashboard
    controller:   App\Controller\UserController
    defaults:
        template: pages/user_dashboard.html.twig
    requirements:
        _locale:  '%locale_available%'