#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path:         /
    controller:   App\Controller\HomeController
    defaults:
        template: pages/home.html.twig

map:
    path:         /map
    controller:   App\Controller\MapController
    defaults:
        template: pages/map.html.twig
#    requirements:
#        _locale:  en|fr

list:
    path:         /list/{page}
    controller:   App\Controller\ListController
    defaults:
        template: pages/list.html.twig
        page:     1

faq:
    path:         /faq
    controller:   App\Controller\FaqController
    defaults:
        template: pages/content.html.twig

sitemap:
    path:         /sitemap
    controller:   App\Controller\SitemapController
    defaults:
        template: pages/content.html.twig

legals:
    path:         /legals
    controller:   App\Controller\LegalsController
    defaults:
        template: pages/content.html.twig

blog:
    path:         /blog/{id}
    controller:   App\Controller\BlogController
    defaults:
        template: pages/content.html.twig
    requirements:
        id:  "[a-zA-Z0-9-]+"

artwork:
    path:         /artwork/{id}
    controller:   App\Controller\ArtworkController
    defaults:
        template: pages/artwork.html.twig
    requirements:
        id:  "[0-9]+"