#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path:         /
    controller:   App\Controller\IndexController
    defaults:
        template: pages/home.html.twig

map:
    path:         /{_locale}/map
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/map.html.twig
    requirements:
        _locale:  en|fr